from __future__ import annotations

"""Bounded website generation and project artifact persistence."""

import json
import re
from dataclasses import dataclass
from typing import Any
from uuid import uuid4

from aethon.ai_provider_fabric import AIProviderFabric
from app.memory_repository import MemoryRepository

@dataclass(frozen=True)
class WebsiteBuild:
    project_id: str
    files: dict[str, str]
    source: str

class WebsiteBuilder:
    def __init__(self, *, ai_fabric: AIProviderFabric | None = None, repository: MemoryRepository | None = None):
        self.ai_fabric = ai_fabric or AIProviderFabric()
        self.repository = repository or MemoryRepository()

    @staticmethod
    def _fallback(prompt: str) -> dict[str, str]:
        title = prompt.strip()[:60] or "AETHON Website"
        safe = re.sub(r"[<>]", "", title)
        html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{safe}</title><link rel="stylesheet" href="styles.css"></head>
<body><main class="hero"><p class="eyebrow">AETHON generated</p><h1>{safe}</h1>
<p>Describe the experience you want and AETHON can refine this website in the next iteration.</p>
<button id="cta">Get started</button></main><script src="app.js"></script></body></html>'''
        css = '''*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:#0b1020;color:#eef2ff}.hero{min-height:100vh;display:grid;place-content:center;gap:16px;max-width:900px;margin:auto;padding:48px}.eyebrow{color:#93c5fd;text-transform:uppercase;letter-spacing:.18em;font-size:12px}h1{font-size:clamp(42px,8vw,84px);margin:0}p{color:#cbd5e1;line-height:1.7;max-width:680px}button{width:max-content;border:0;border-radius:12px;padding:14px 20px;background:#2563eb;color:white;font-weight:700;cursor:pointer}'''
        js = '''document.querySelector('#cta')?.addEventListener('click',()=>alert('Built by AETHON.'));'''
        return {"index.html":html,"styles.css":css,"app.js":js,"README.md":f"# {safe}\n\nGenerated by AETHON.\n"}

    @staticmethod
    def _parse(text: str) -> dict[str, str] | None:
        candidate=text.strip()
        fence=re.search(r"```(?:json)?\s*(\{.*?\})\s*```", candidate, re.S|re.I)
        if fence: candidate=fence.group(1)
        try: data=json.loads(candidate)
        except json.JSONDecodeError: return None
        files=data.get("files") if isinstance(data,dict) else None
        if not isinstance(files,dict): return None
        allowed={"index.html","styles.css","app.js","README.md"}
        clean={}
        for name,value in files.items():
            if name in allowed and isinstance(value,str) and value.strip() and len(value)<=120000:
                clean[name]=value
        return clean if "index.html" in clean else None

    def _generate(self, prompt: str) -> tuple[dict[str,str],str]:
        instruction=(
            "Create a complete small production-ready static website from the user request. "
            "Return ONLY JSON with a files object. Allowed files are index.html, styles.css, app.js, README.md. "
            "index.html must reference styles.css and app.js. Keep each file self-contained, accessible and responsive. "
            "Do not include markdown fences or explanations. User request: " + prompt
        )
        if self.ai_fabric.list():
            try:
                result=self.ai_fabric.generate(instruction,user_text=prompt)
                files=self._parse(result.text)
                if files: return files,"ai"
            except Exception:
                pass
        return self._fallback(prompt),"template"

    def build(self, prompt: str, *, owner_id: str, project_id: str | None = None) -> WebsiteBuild:
        if not prompt.strip(): raise ValueError("website prompt cannot be empty")
        target_project=project_id or str(uuid4())
        files,source=self._generate(prompt)
        payload=json.dumps({"project_id":target_project,"prompt":prompt.strip(),"files":files,"source":source})
        self.repository.put("website:"+target_project,payload,owner_id=owner_id,project_id=project_id,namespace="website_artifacts",memory_type="website",source="website_builder",confidence=1.0)
        return WebsiteBuild(target_project,files,source)

    def get(self, project_id: str, *, owner_id: str) -> WebsiteBuild | None:
        records=self.repository.list_scope(owner_id=owner_id,project_id=project_id,namespace="website_artifacts",limit=20)
        record=next((r for r in records if r.memory_id=="website:"+project_id),None)
        if record is None: return None
        data=json.loads(record.content)
        return WebsiteBuild(project_id,data.get("files",{}),str(data.get("source","stored")))

    def artifact(self, build: WebsiteBuild) -> dict[str,Any]:
        return {"type":"website","project_id":build.project_id,"files":build.files,"entrypoint":"index.html"}

    @staticmethod
    def _edit_fallback(files: dict[str, str], instruction: str) -> dict[str, str]:
        lowered = instruction.casefold()
        result = dict(files)
        if "remove button" in lowered or "remove the button" in lowered:
            result["index.html"] = re.sub(r"<button[^>]*>.*?</button>", "", result.get("index.html", ""), flags=re.S|re.I)
        if "dark" in lowered and "background:" not in result.get("styles.css", ""):
            result["styles.css"] = "body{background:#0b1020;color:#eef2ff;}\n" + result.get("styles.css", "")
        return result
    def update(self, project_id: str, instruction: str, *, owner_id: str) -> WebsiteBuild:
        current = self.get(project_id, owner_id=owner_id)
        if current is None:
            raise ValueError("website project not found")
        prompt = (
            "Modify this existing website according to the user's request. "
            "Preserve unrelated behavior and return ONLY JSON with a files object. "
            "Allowed files: index.html, styles.css, app.js, README.md. "
            f"User request: {instruction}\nExisting files:\n"
            + json.dumps(current.files)
        )
        files, source = self._generate(prompt)
        if source == "template":
            files = self._edit_fallback(current.files, instruction)
        self.repository.put(
            "website:" + project_id,
            json.dumps({"project_id": project_id, "prompt": instruction.strip(), "files": files, "source": source}),
            owner_id=owner_id, project_id=project_id, namespace="website_artifacts",
            memory_type="website", source="website_builder", confidence=1.0,
        )
        return WebsiteBuild(project_id, files, source)